// src/leaderboardData.js
const leaderboardData = [
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  { name: "Alice", score: 120 },
  { name: "Bob", score: 105 },
  { name: "Carol", score: 90 },
  // ...more players
];

export default leaderboardData;
